--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonw4331/EasyCommandAutofill
build-by-default: true
projects:
  EasyCommandAutofill:
    path: ""
    icon: "icon.png"
    excludeDirs:
      - .github
    excludeFiles:
      - .gitignore
      - CONTRIBUTING.md
      - SECURITY.md
      - phpstan.neon.dist
      - phpstan-baseline.php
      - .php-cs-fixer.php
    libs:
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: ^0.1
...
