name: EasyCommandAutofill
main: jasonwynn10\EasyCommandAutofill\Main
version: 0.1.0
api: 3.0.0
mcpe-protocol:
 - 389
description: "A plugin which adds commands to the client's autofill by parsing usage messages"
author: "jasonwynn10"