####################################################################################################################################################
#    _____                          ____                                                       _      _              _              __   _   _   _ #
#  | ____|   __ _   ___   _   _   / ___|   ___    _ __ ___    _ __ ___     __ _   _ __     __| |    / \     _   _  | |_    ___    / _| (_) | | | | #
# |  _|    / _` | / __| | | | |  | |      / _ \  | '_ ` _ \  | '_ ` _ \   / _` | | '_ \   / _` |   / _ \   | | | | | __|  / _ \  | |_  | | | | | | #
# | |___  | (_| | \__ \ | |_| | | |___  | (_) | | | | | | | | | | | | | | (_| | | | | | | (_| |  / ___ \  | |_| | | |_  | (_) | |  _| | | | | | |  #
#|_____|  \__,_| |___/  \__, |  \____|  \___/  |_| |_| |_| |_| |_| |_|  \__,_| |_| |_|  \__,_| /_/   \_\  \__,_|  \__|  \___/  |_|   |_| |_| |_|   #
#                       |___/                                                                                                                      #
####################################################################################################################################################

# Debug Command Highlighting
# When enabled, a selection of debugging commands will be highlighted blue in the autofill
Highlight Debugging Commands: false

# Generate the default command enums
# When enabled, the plugin will generate the default command enums such as item names and effects
Generate Default Enums: true

# Generate the command PocketMine autofill
# When enabled, the plugin will generate the autofill command information for PocketMine's default commands
Generate PocketMine Command Autofill: true